// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzVaulrXQZxU04Wy8awayS9wVQOmzxw1Q',
    appId: '1:214993471933:web:3e33c70b94ec5d2ddeaad4',
    messagingSenderId: '214993471933',
    projectId: 'prsrin-app',
    authDomain: 'prsrin-app.firebaseapp.com',
    storageBucket: 'prsrin-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaDV08bbMVrnz7zeSstAsv7N2xbu0pTcI',
    appId: '1:214993471933:android:b1f2122bc390725bdeaad4',
    messagingSenderId: '214993471933',
    projectId: 'prsrin-app',
    storageBucket: 'prsrin-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw96OzPAFbDOIdaAHX9cs66gOp7jtFNwo',
    appId: '1:214993471933:ios:31a93bddd9eb6264deaad4',
    messagingSenderId: '214993471933',
    projectId: 'prsrin-app',
    storageBucket: 'prsrin-app.appspot.com',
    iosClientId: '214993471933-i1urvj1kr2tsu5tl4ffs62qvkg1ok3vg.apps.googleusercontent.com',
    iosBundleId: 'app.datacode.prsin.prsin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw96OzPAFbDOIdaAHX9cs66gOp7jtFNwo',
    appId: '1:214993471933:ios:31a93bddd9eb6264deaad4',
    messagingSenderId: '214993471933',
    projectId: 'prsrin-app',
    storageBucket: 'prsrin-app.appspot.com',
    iosClientId: '214993471933-i1urvj1kr2tsu5tl4ffs62qvkg1ok3vg.apps.googleusercontent.com',
    iosBundleId: 'app.datacode.prsin.prsin',
  );
}
